Making changes necessary to make the server run on OSGi again. I appreciate people not breaking this mode any more. The changes are described below: 1. core/kernel/pom.xml: added dependency on dol, because ApplicationLifecycle depends on dol. Without this change, server was throwing following exception: java.lang.LinkageError: Failed to inject class com.sun.enterprise.v3.services.impl.ApplicationLoaderService from 21.0 Caused by: java.lang.NoClassDefFoundError: com/sun/enterprise/deployment/Application
2. core/security/pom.xml: added dependency on internal-api. WIthout this, serverwas throwing following exception:
Exception while deploying the app
org.jvnet.hk2.component.UnsatisfiedDepedencyException: Unsatisfied dependency exception : private com.sun.enterprise.security.SecurityServicesUtil com.sun.enterprise.security.SecurityLifecycle.secServUtil
        at org.jvnet.hk2.component.InjectionManager.inject(InjectionManager.java:100)
Caused by: org.jvnet.hk2.component.ComponentException: Failed to create class com.sun.enterprise.security.SecurityServicesUtil
        at com.sun.hk2.component.ConstructorWomb.create(ConstructorWomb.java:76)
Caused by: java.lang.NoClassDefFoundError: org/glassfish/internal/api/Globals
        at com.sun.enterprise.security.SecurityServicesUtil.<clinit>(SecurityServicesUtil.java:61)

3.distributions/external/grizzly-http/pom.xml: Changed pom.xml to not import
com.sun.grizzly.standalone.servlet, as this package is not available. Without
this change, server won't start as grizzly-module could not be resolved.

4. core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/*.java:
Ported changes made by Jerome in tp2 branch to trunk. That was necessary for
a successful run of QL on Felix mode, as QL expects derby drivers to be
available in common class loader.

QL now passes, both on HK2 as well as Felix. Don't break it.