Removing dependency on gmbal-api.  This an old API and should not be used.  We should use the exising gmbal.  Otherwise, gmbal-api.jar will conflict with the existing gmbal.jar, and will see a NoSuchMethodError.  This is breaking the monitoring mbeans.