1) Tweaked error and success messages 2) It now allows restoring a domain to a different domain name
A) Bug 6505206
BEFORE

C:\temp>asadmin restore-domain --domaindir domains domain1
Successfully restored the domain (domain1), from C:\temp\domains\domain1\backups\sjsas_backup_v00001.zip
Description: 1171681302296
Backup Filename: C:\as\domains\domain1\backups\sjsas_backup_v00001.zip
Date and time backup was performed: Fri Feb 16 19:01:42 PST 2007
Domains Directory: C:\as\domains
Domain Directory: C:\as\domains\domain1
Domain Name: domain1
Name of the user that performed the backup: bnevins

----------------------------------------------------------------

After:

C:\temp>asadmin restore-domain --domaindir domains domain1
Successfully restored the domain, domain1, to C:\temp\domains\domain1
Description: 1171681302296
Backup Filename: C:\as\domains\domain1\backups\sjsas_backup_v00001.zip
Date and time backup was performed: Fri Feb 16 19:01:42 PST 2007
Domains Directory: C:\as\domains
Domain Directory: C:\as\domains\domain1
Domain Name: domain1
Name of the user that performed the backup: bnevins

-------------------------------------------------------------------------------------------------------------------------

B) Bug 6515398

AFTER Fixing the bug:

(1) the backup-file doesn't exist:

C:\jws\glassfish>asadmin restore-domain --filename c:/as/domains/domain1/backups/sjsas_backup_v00003x.zip domain24
Usage: restore-domain [--domaindir domain_directory] [--filename backup_filename]  [--description description] [--terse=false] [--ec
ho=false] [--verbose=false] [domain_name]
CLI146 c:/as/domains/domain1/backups/sjsas_backup_v00003x.zip does not exist in the file system or read permission denied.

(2) point to a garbage file:

C:\jws\glassfish>asadmin restore-domain --filename junk.zip domain24
com.sun.enterprise.config.backup.BackupException: The specified backup file (C:\jws\glassfish\junk.zip) is corrupt.  Try another bac
kup file.