Bug 6333483 Description:
StandAlone clients happens to use PEPluggableFeatureFactory for getting
security utilities in SSL socket factory. PEPluggableFeatureFactory
had an unwanted reference to ASLazyKernel. When new apis are added to
ASLazyKernel 9.0, those standalone clients which did not have appserv-admin.jar
in the classpath started throwing NoClassDefFoundError. This fix is to remove
ASLazyKernel refernce from PEPluggableFeatureFactory.

Reviewed by: Kedar, Sankar

Tests : PE QL on PE installation, EE QL on EE installation, PE QL with quickstartup
        turned off.